Fix build failure on macOS
freebsd/kyua pull request #226
Opened 2024-03-10 22:50 UTC by fel1x-developer

Solves #219

2024-05-05 11:57 UTC, ngie-eign requested changes
A number of autogenerated files are being committed as part of this change that should not be committed:
- `admin/config.guess`
- `admin/config.sub`
- `admin/ltmain.sh`
Getting to the change at hand... what's the issue that you're running into MacOS? That part isn't clear from the proposed change.
Sidenote: your `--prefix` isn't standard for (some versions of?) Homebrew; this is part of the reason why these generated files should not be committed to the source tree.

2024-05-05 12:03 UTC, ngie-eign commented
I looked a bit closer and the issue provides more detail, as well as the commit messages themselves.. but it was missing from the PR description. Providing this context next time in the PR summary would make it easier for me to understand (without having to dive too deep into the details) what is being done.

_(I'm partly dropping this concern, because PR descriptions are only really maintained in the GH UI/ecosystem)_

The autogenerated files should still be removed.

2024-05-05 12:16 UTC, ngie-eign commented on .gitignore
> +/ltmain.sh
```suggestion
ltmain.sh
```

2024-05-05 12:17 UTC, ngie-eign commented on .gitignore
> +/config.sub
```suggestion
config.sub
```

2024-05-05 12:17 UTC, ngie-eign commented on .gitignore
> +/config.guess
```suggestion
config.guess
```

2024-05-05 12:28 UTC, ngie-eign commented on configure.ac
> +LT_INIT
This diff needs to be applied to mute complaints from autotools: https://gist.github.com/ngie-eign/882b78bc57a6b4e50ad224a6394df5e1 . Could you please add this as a [fixup commit](https://mikulskibartosz.name/git-fixup-explained), squash it and other changes I've added to your branch, and rebase with the latest version of master?

2024-05-06 16:05 UTC, ngie-eign approved these changes

2024-05-06 16:05 UTC, merged

2024-05-27 11:15 UTC, ihoro commented
Hi @fel1x-developer . Could you please share the way you build it for macOS? I would like to repeat the build for testing of recent changes in Kyua. The list of steps, dependencies, versions, etc -- anything will be useful. For instance, I use `atf` installed via `homebrew`.

My motivation: I see that FreeBSD based build is broken (I'm not sure yet whether it's my local issue or due to recent change in *.ac *.am), I would like to fix it and make sure that macOS based build still is fine. And I would like to keep macOS based build tested during the future changes of Kyua.

2024-05-30 04:08 UTC, fel1x-developer commented
> Hi @fel1x-developer . Could you please share the way you build it for macOS? I would like to repeat the build for testing of recent changes in Kyua. The list of steps, dependencies, versions, etc -- anything will be useful. For instance, I use `atf` installed via `homebrew`.
> 
> My motivation: I see that FreeBSD based build is broken (I'm not sure yet whether it's my local issue or due to recent change in *.ac *.am), I would like to fix it and make sure that macOS based build still is fine. And I would like to keep macOS based build tested during the future changes of Kyua.

Hi @ihoro !

First install `lutok`, `atf`, and `lua` with homebrew. Then, build lutok and atf in `~/local` with
```shell
$ autoreconf -i -s -I ~/local/share/aclocal
$ ./configure --prefix ~/local
$ make -j4
$ make install
```

Using the same method, you can build kyua at `~/local` (Don't forget `autoreconf` and `./configure` options)

Feel free to ask me if you have any question!

2024-05-30 06:37 UTC, ihoro commented
Thanks for the information. It looks we do it almost the same way. The only diff is that I was using atf as is from `homebrew` without explicit build. I guess it should not be a significant difference.

By the way, from the end user perspective, you use a custom build for your production/personal needs because of:
a) custom patches
b) outdated version from `homebrew` without recent fixes
c) other reasons?

2024-05-31 02:46 UTC, fel1x-developer commented
Mainly b). New versions of `lutok`, `atf`, and `kyua` should be released ASAP to make them installable and executable from Homebrew. I will work on updating those three formulas when new versions of lutok, atf, and kyua come out.

2024-05-31 08:39 UTC, ihoro commented
Thank you very much for the outline of your use cases. And kudos for the homebrew formulas maintenance. I have hopes that Kyua could get a new version this summer.