Do not count skipped as passed in test cmd
freebsd/kyua pull request #230
Opened 2024-09-25 09:49 UTC by ihoro

```
It changes only output of 'kyua test' CLI command. Hence, other outputs
like junit are kept intact for CI and other use cases. It's meant to
improve UX of attended use cases.

The issue is that the following can be tricky to interpret:

  222/222 passed (0 failed)

It can be read as all tests are passed, but it might be a summary line
of all tests skipped due to some requirement is not met.

It's reworked to easily distinguish such cases:

  222/222 passed (0 broken, 0 failed, 0 skipped)
  0/222 passed (0 broken, 0 failed, 222 skipped)

The overall formula is:

  <actually passed>/<total> (<details about not actually passed ones>)
```

2024-09-25 09:49 UTC, ihoro commented
It mirrors https://reviews.freebsd.org/D46653.

2024-11-13 20:57 UTC, emaste commented
I prefer the reporting that @kprovost suggested in the FreeBSD review. "7/7 passed (and 3 were skipped)" is more immediately obvious to me than "7/10 passed (the three that did not pass were skipped)." Or don't print as a ratio. "7 passed, 0 failed, 3 skipped, 10 total"

2024-12-01 18:23 UTC, ngie-eign requested changes
I'm on board with @emaste . This format change can result in user confusion about how many failures there actually were when executing tests.

2026-09-02 21:55 UTC, ngie-eign approved these changes
Merging the change to achieve parity with what's committed to freebsd:main. We'll probably get feedback if folks don't like the new UI in a later GH issue...

2026-09-02 21:56 UTC, merged