Add initial GitHub Actions support for kyua
freebsd/kyua pull request #254
Opened 2024-12-29 18:42 UTC by ngie-eign

This proposed GitHub Actions workflow file runs tests on MacOS and Ubuntu Linux, similar to what is being proposed in https://github.com/freebsd/atf/pull/93 .

The delta between this change and the one being made in ATF mostly relates to the additional package dependencies, e.g., with and without ATF.

Kyua is built from scratch because of issues with dependent packages and runtime linker collisions on both MacOS and Ubuntu. The binary package versions are built against a different version of Lutok, ergo they can have runtime linker collisions.

2024-12-30 15:22 UTC, asomers commented
Why neglect the primary target platform?  We could easily do CI on FreeBSD using Cirrus CI instead of Github Actions.

2024-12-30 16:06 UTC, ngie-eign commented
> Why neglect the primary target platform? We could easily do CI on FreeBSD using Cirrus CI instead of Github Actions.

I have an issue filed to reenable Cirrus CI. The goal of adding GH actions and Cirrus CI is to cover Linux and MacOS because the tooling for LLVM isn’t there on FreeBSD, and a lot of the GH issues being filed are coming from Linux and MacOS users.
But yes, I need to enable Cirrus CI on my local fork and resolve issues with the current config, given that the config has grown stale over time.

2024-12-30 16:24 UTC, asomers requested changes

2024-12-30 16:24 UTC, asomers commented on .github/workflows/build.yaml
> +                      enable-atf-pkgs:
Since the below line is commented out, add brackets to make this valid YAML
```suggestion
                      enable-atf-pkgs: []
```

2024-12-30 16:27 UTC, asomers commented
> I have an issue filed to reenable Cirrus CI. The goal of adding GH actions is to cover Linux and MacOS because the tooling for LLVM isn’t there on FreeBSD, and a lot of the GH issues being filed are coming from Linux and MacOS users. But yes, I need to enable Cirrus CI on my local fork and resolve issues with the current config, given that the config has grown stale over time.

Oh, I didn't notice that issue.  But yes, this PR looks fine for Linux and OSX

2025-01-06 09:24 UTC, ihoro commented on .github/workflows/build.yaml
> +    ATF_REF: atf-0.22
I would propose to build and test it against development branches of atf and lutok. It could add chances that it's tested against the recent changes in the dependencies sooner, not to get surprised much later during release engineer etc. If required, a release could be a separate branch tagged where this config is changed to strict versions. Another option is to make GHA matrix include the latest versions (master/main) plus the latest released version -- that's for cases when Kyua could link & use non-latest version of dependencies.

Perhaps, we should finish s/master/main/ for all three projects first (like this: https://github.com/freebsd/atf/issues/94), not to come back here due to failed jobs or so.

2025-01-06 09:25 UTC, ihoro commented on .github/workflows/build.yaml
> +    LUTOK_REF: build-cleanup
I guess it will eventually switch back to the freebsd/lutok repo. It may stay like this unnoticed for long time w/o expected outcome of CI builds.

2026-09-02 02:22 UTC, ngie-eign commented on .github/workflows/build.yaml
> +    LUTOK_REF: build-cleanup
Updated/fixed.

2026-09-02 02:25 UTC, ngie-eign commented
> > I have an issue filed to reenable Cirrus CI. The goal of adding GH actions is to cover Linux and MacOS because the tooling for LLVM isn’t there on FreeBSD, and a lot of the GH issues being filed are coming from Linux and MacOS users. But yes, I need to enable Cirrus CI on my local fork and resolve issues with the current config, given that the config has grown stale over time.
> 
> Oh, I didn't notice that issue. But yes, this PR looks fine for Linux and OSX

I ended up taking the vmactions route on freebsd/atf and freebsd/lutok instead of Cirrus CI, especially since Cirrus CI has now been shut down.

2026-09-02 21:57 UTC, ngie-eign commented on .github/workflows/build.yaml
> +    ATF_REF: atf-0.22
This would be ideal, but I'd rather start with release versions first, then migrate to building off HEAD.
FWIW, we already have the opposite problem with atf and lutok in those respective projects (they build using whatever the latest release is for atf, kyua, and lutok respectively).
Part of the problem boils down to resources and time needed to get signal when submitting PRs. I want to get this in to avoid having to retroactively fix issues found in #286 , et al.

2026-09-03 03:12 UTC, ngie-eign commented on .github/workflows/build.yaml
> +                      enable-atf-pkgs:
I removed the line entirely because you can't run `make dist` without ATF. I kind of don't know why the option even really exists TBH.

2026-09-03 21:31 UTC, ngie-eign commented
I hit a number of problems preparing for 0.15.0 which would have been caught by CI if it had been enabled on the repo (examples: fd1622f301625f0f5bdc57277622a63eb2c7c14f, #286, #289... the list goes on).
Hopefully adding a GHA workflow to the project will help shine a light on a number of issues with proposed changes.

2026-09-04 07:21 UTC, merged